### ISSUE TITLE
Example override

### ISSUE THREAD

**Issue by skeet70** [BatteredBunny/brew-nix#13]
The readme mentions needing to override packages to set their hash if missing. An example of doing that would be helpful. I'm a nix beginner-intermediate and I've been trying the ways I've overridden/overlaid packages in the past, but have so far failed to set the hash.

**Comment by xav-ie** [comment]
You can do it like this:
https://github.com/xav-ie/dots/blob/b102f6143d0c65069199751a0d7515aca017cc18/modules/home-manager/darwin/default.nix#L16-L21

with overrideAttrs, you kind of have to redefine the whole thing, that is why I must grab the previous `src`. I am no nix expert either, but this works.
