### ISSUE TITLE
Outdated README package path examples

### ISSUE THREAD

**Issue by charlieegan3** [BatteredBunny/brew-nix#6]
Edit: I have updated the title after some feedback from another commenter below.

Firstly, thanks for making this interesting project. I haven't got it to work yet, but I am interested in the idea and think it could be valuable for many others.

I am encountering an issue with my flake.nix configuration. Here is, I think, a minimal example:

```nix
{
  description = "My Home Manager Configuration";

  inputs = {
    nixpkgs.url = "github:nixos/nixpkgs/nixos-unstable";
    home-manager.url = "github:nix-community/home-manager";
    brew-nix = {
      url = "github:BatteredBunny/brew-nix";
      inputs.brew-api.follows = "brew-api";
    };
    brew-api = {
      url = "github:BatteredBunny/brew-api";
      flake = false;
    };
  };

  outputs = { nixpkgs, home-manager, brew-nix, ... }:
    let
      system = "aarch64-darwin";
      pkgs = import nixpkgs {
        inherit system;
        overlays = [ brew-nix.overlays.default ];
      };
    in
    {
      homeConfigurations."my_user" = home-manager.lib.homeManagerConfiguration {
        inherit pkgs;
        modules = [
          ./home.nix
          {
            home.packages = with pkgs; [ brewCasks.marta ];
          }
        ];
      };
    };
}
```

However, I get this error for any cask I try.

```sh
       error: attribute 'marta' missing
       at /nix/store/fq0lbkk91jzacx4240nqxbxqqsjadi7w-source/flake.nix:31:42:
           30|           {
           31|             home.packages = with pkgs; [ brewCasks.marta ];
             |                                          ^
           32|           }
```

If you have any ideas on how to resolve this issue, I would greatly appreciate your help!

**Comment by christian-burger** [comment]
Had the same problem. All packages are declared under an attribute specifying the arch as you can see [here in the source](https://github.com/BatteredBunny/brew-nix/blob/0b084fb3a92ec782a67f21110333fc2480d1285c/flake.nix#L24). The example seems to be outdated. This here should succeed: `brewCasks.${system}.marta`.

What helps me in those cases is using `builtins.trace`. In your case you could replace `brewCasks.marta` with `(builtins.trace brewCasks brewCasks.marta)` to see what's to be found in `brewCasks`. On the next run you would see something along the lines of `trace: { aarch64-darwin = <CODE>; aarch64-linux = <CODE>; x86_64-darwin = <CODE>; x86_64-linux = <CODE>; }` just above the actual error message.

I would recommend leaving the issue open and clarifying the title along the lines: "example in `README.md`is outdated`.

**Comment by charlieegan3** [comment]
Thanks for the input here, I was able to get this working with your suggested changes! I’ll leave this open.

**Comment by BatteredBunny** [comment]
I made a PR that should make it work as expected in README.md, i haven't tested it myself yet so please check it out.

**Comment by charlieegan3** [comment]
I have been able to test with the commit 5387a4fff65d313e82c24bdc856847532e052ea4 and it works for me! thanks for looking into it.

**Comment by pinage404** [comment]
My bad, i'm sorry about that

**Comment by charlieegan3** [comment]
Looks to be fixed now so you're all good :) and I'm very happy I've got it working now. Just wired it up with [mac-app-util ](https://github.com/hraban/mac-app-util) too and it works great.
